services:
  cakap:
    build:
      context: .
      dockerfile: coolify.Dockerfile
    container_name: cakap
    restart: always
    environment:
      # Sesuaikan environment CodeIgniter di sini
      - ENVIRONMENT=production
      - DB_HOST=awg44s8840kw4kssk048ss4g
      - DB_USER=cakap
      - DB_PASS=7P1q]zzTJSQ1hvAe
      - DB_NAME=cakap
      - SSO_CLIENT_ID=CAKAP
      - SSO_CLIENT_SECRET=p6llLPomY32f8RYJE14eqM2AMuqLZ53N
      - SSO_REDIRECT_URL=https://cakap.kanwilkemenagdiy.id/sso/callback
      - SSO_AUTH_URL=https://sso.kanwilkemenagdiy.id/realms/master/protocol/openid-connect/auth
      - SSO_TOKEN_URL=https://sso.kanwilkemenagdiy.id/realms/master/protocol/openid-connect/token
      - SSO_USER_INFO_URL=https://sso.kanwilkemenagdiy.id/realms/master/protocol/openid-connect/userinfo
      - SSO_LOGOUT_URL=https://sso.kanwilkemenagdiy.id/realms/master/protocol/openid-connect/logout
      - SSO_HOME_URL=https://cakap.kanwilkemenagdiy.id
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 15
    networks:
      - coolify

networks:
  coolify:
    external: true
